export function getRandomName() {
  const [randomNoun, gender] = nouns[Math.floor(Math.random() * nouns.length)]!;
  const randomAdjectives =
    adjectives[Math.floor(Math.random() * adjectives.length)]!;
  return `${randomAdjectives[gender]} ${randomNoun}`;
}
const nouns: [string, 0 | 1 | 2][] = [
  ["pies", 0],
  ["kot", 0],
  ["krokodyl", 0],
  ["wąż", 0],
  ["kangur", 0],
  ["koń", 0],
  ["kura", 1],
  ["kaczka", 1],
  ["sowa", 1],
  ["wilk", 0],
  ["lew", 0],
  ["tygrys", 0],
  ["ryś", 0],
  ["puma", 1],
  ["lampart", 0],
  ["gepard", 0],
  ["nosorożec", 0],
  ["hipopotam", 0],
  ["żyrafa", 1],
  ["zebra", 1],
  ["słoń", 0],
  ["niedźwiedź", 0],
  ["panda", 1],
  ["koala", 0],
  ["pingwin", 0],
  ["surykatka", 1],
  ["wiewiórka", 1],
  ["jeż", 0],
  ["zając", 0],
  ["lis", 0],
  ["wilk", 0],
  ["kuna", 1],
  ["szop", 0],
  ["borsuk", 0],
  ["kret", 0],
  ["nietoperz", 0],
  ["jeleń", 0],
  ["łoś", 0],
  ["sarna", 1],
];
const adjectives: [string, string, string][] = [
  ["zielony", "zielona", "zielone"],
  ["czerwony", "czerwona", "czerwone"],
  ["niebieski", "niebieska", "niebieskie"],
  ["żółty", "żółta", "żółte"],
  ["różowy", "różowa", "różowe"],
  ["fioletowy", "fioletowa", "fioletowe"],
  ["pomarańczowy", "pomarańczowa", "pomarańczowe"],
  ["brązowy", "brązowa", "brązowe"],
  ["czarny", "czarna", "czarne"],
  ["biały", "biała", "białe"],
  ["szary", "szara", "szare"],
  ["srebrny", "srebrna", "srebrne"],
  ["złoty", "złota", "złote"],
  ["tęczowy", "tęczowa", "tęczowe"],
  ["jasny", "jasna", "jasne"],
  ["ciemny", "ciemna", "ciemne"],
  ["mały", "mała", "małe"],
  ["duży", "duża", "duże"],
  ["gruby", "gruba", "grube"],
  ["chudy", "chuda", "chude"],
  ["szybki", "szybka", "szybkie"],
  ["wolny", "wolna", "wolne"],
  ["mądry", "mądra", "mądre"],
  ["szalony", "szalona", "szalone"],
  ["szczęśliwy", "szczęśliwa", "szczęśliwe"],
];
